MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feed import ArticleFeed
from blog.views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'', include('comments.urls', namespace='comments')),
    url(r'^rss/$', ArticleFeed(), name='rss'),
    url(r'^search/', include('haystack.urls'))
]

apps/blog/urls.py
from django.conf.urls import url
from .views import IndexView, ArticleDetailView, ArchivesView, CategoryView, AboutView
from .views import search

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^detail/(?P<id>\d+)/$', ArticleDetailView.as_view(), name='detail'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)/$', ArchivesView.as_view(), name='archive'),
    url(r'^category/(?P<id>\d+)/$', CategoryView.as_view(), name='category'),
    url(r'^about/$', AboutView.as_view(), name='about'),
]

apps/comments/urls.py
from django.conf.urls import url
from .views import CommentView

urlpatterns = [
    url(r'^commit/(?P<id>\d+)/$', CommentView.as_view(), name='commit'),
]

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.shortcuts import reverse
from django.utils.html import strip_tags
import markdown
from django.utils import timezone


class Category(models.Model):
    ''' 文章分类 '''
    name = models.CharField(max_length=100, verbose_name='分类名')

    def __str__(self):
        return self.name

    def get_articles(self):
        ''' 返回这个分类下的所有文章 '''
        return self.article_set.all()

    def get_art_nums(self):
        ''' 返回分类下的文章的数量 '''
        return self.article_set.all().count()


class Tag(models.Model):
    ''' 文章标签 多对多 '''
    name = models.CharField(max_length=100, verbose_name='标签名')

    def __str__(self):
        return self.name


class Article(models.Model):
    ''' 博客文章 '''
    title = models.CharField(max_length=60, verbose_name='文章标题')
    content = models.TextField(verbose_name='文章内容')
    create_time = models.DateField(default=timezone.now, verbose_name='创建时间')
    modify_time = models.DateField(default=timezone.now, verbose_name='修改时间')
    excerpt = models.CharField(max_length=300, blank=True, verbose_name='文章摘要')

    tags = models.ManyToManyField(Tag, blank=True, verbose_name='文章标签')
    categorys = models.ForeignKey(Category, verbose_name='文章分类')
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型
    author = models.ForeignKey(User, verbose_name='作者')
    click_nums = models.IntegerField(verbose_name='阅读数', default=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'id': self.id})

    class Meta:
        ordering = ['-create_time', 'title']

    def increase_views(self):
        self.click_nums += 1
        self.save(update_fields=['click_nums'])

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.content))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Article, self).save(*args, **kwargs)

apps/comments/models.py
from django.db import models
from blog.models import Article


class Comment(models.Model):
    name = models.CharField(max_length=100, verbose_name='用户名')
    email = models.EmailField(max_length=255, verbose_name='邮箱')
    url = models.URLField(blank=True, verbose_name='个人网站')
    text = models.TextField(verbose_name='评论内容')  # auto_now_add 的作用是，当评论数据保存到数据库时，自动把 created_time 的值指定为当前时间
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    article = models.ForeignKey(Article, related_name='comm_artc')
    s = models.FileField()

    def __str__(self):
        return self.name + ': ' +self.text[:20]

apps/comments/forms.py
from django import forms
from comments.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import HttpResponse
import markdown
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q

from .models import Article, Category
from comments.forms import CommentForm
from comments.models import Comment

from pure_pagination import Paginator, PageNotAnInteger


class IndexView(View):
    def get(self, request):
        all_article = Article.objects.all()
        # 分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_article, 3, request=request)
        articles = p.page(page)

        context = {
            'articles': articles,
        }
        return render(request, 'index.html', context)


class ArticleDetailView(View):
    ''' 文章详情处理View '''
    def get(self, request, id):
        article = get_object_or_404(Article, pk=id)   # 返回404表示文章不存在
        if article and article != 404:

            article.increase_views()
            # 把 Markdown 文本转为 HTML 文本再传递给模板
            md = markdown.Markdown(extensions=[
                                                'markdown.extensions.extra',     #
                                                'markdown.extensions.codehilite',  # 语法高亮
                                                TocExtension(slugify=slugify),  # 自动生成目录
                                                ])
            article.content = md.convert(article.content)
            article.toc = md.toc
            form = CommentForm()
            comment_list = Comment.objects.filter(article=article)

            context = {
                'article': article,
                'form': form,
                'comment_list': comment_list,
            }
            return render(request, 'detail.html', context)


class ArchivesView(View):
    ''' 归档处理view '''
    def get(self, request, year, month):
        # 使用mysql时无法查询， 需要MySQL：安装pytz，并使用mysql_tzinfo_to_sql加载时区表，看queryapi中的datetimes
        articles = Article.objects.filter(create_time__year=year, create_time__month=month)
        context = {
            'articles': articles,
        }
        return render(request, 'index.html', context)


class CategoryView(View):
    ''' 分类VIew'''

    def get(self, request, id):
        category = get_object_or_404(Category, pk=id)
        articles = category.get_articles()
        context = {
            'articles': articles,
        }
        return render(request, 'index.html', context)


class AboutView(View):

    def get(self, request):
        return render(request, 'about.html')


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键字'
        return render(request, 'index.html', {'error_msg': error_msg})
    articles = Article.objects.filter(Q(title__icontains=q)|Q(content__icontains=q))
    context = {
        'error_msg': error_msg,
        'articles': articles,
    }
    return render(request, 'index.html', context)

apps/comments/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect,reverse
from django.views import View
from blog.models import Article
from .forms import CommentForm
from django.http import  HttpResponseRedirect


class CommentView(View):
    ''' 评价视图 '''
    def post(self, request, id):
        article = get_object_or_404(Article, pk=id)

        form = CommentForm(request.POST)
        if form.is_valid():
            # commit = False的作用是仅仅利用表单的数据生成
            # Comment模型类的实例，但还不保存评论数据到数据库。
            comment = form.save(commit=False)
            # 将评论文章关联
            comment.article = article
            comment.save()
            return HttpResponseRedirect(article.get_absolute_url())

apps/blog/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% block content %}

    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                    </h1>
                    <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' result.object.categorys.pk %}">
                            {{ result.object.category.name }}</a></span>
                        <span class="post-date"><a href="#">
                            <time class="entry-date" datetime="{{ result.object.created_time }}">
                                {{ result.object.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                        <span class="comments-link">
                        <a href="{{ result.object.get_absolute_url }}#comment-area">
                            {{ result.object.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a
                                href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{% highlight result.object.content with query %}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}

{% endblock content %}

{% block right %}
{% endblock right %}

templates/blog/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% load blog_tags %}
<head>

    <title>Black &amp; White</title>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'home' %}"><b>acutesun</b></a></h1>
                </div>

            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'home' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="{% url 'haystack_search' %}"><span id="search-icon"
                                                                                 class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
<div class="content-body">
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}

            {% block right %}
                <aside class="col-md-4">
                    <div class="widget widget-recent-posts">
                        {% get_new_articles as news %}
                        <h3 class="widget-title">最新文章</h3>
                        <ul>
                            {% for new in news %}
                                <li>
                                    <a href="{% url 'blog:detail' new.id %}">{{ new.title }}</a>
                                </li>
                            {% empty %}
                                暂无文章！
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        {% archives as archs %}
                        <ul>
                            {% for archive in archs %}
                                <li>
                                    <a href="{% url 'blog:archive' archive.year archive.month %}">
                                        {{ archive.year }}年{{ archive.month }}月({{ archive.nums }})</a>
                                </li>
                            {% empty %}
                                暂无归档
                            {% endfor %}

                        </ul>

                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        <ul>
                            {% get_categories as cats %}
                            {% for category in cats %}
                                <li>
                                    <a href="{% url 'blog:category' category.id %}"> {{ category.name }}
                                        <span class="post-count">({{ category.article_nums }})</span></a>
                                </li>

                            {% empty %}
                                暂无分类！
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        <ul>
                            {% get_tags as tags %}
                            {% for tag in tags %}
                                <li>
                                    <a href="#">{{ tag.name }}</a>
                                </li>
                            {% empty %}
                                暂无标签！
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            {% endblock %}
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">首页</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/blog/single.html
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body id="single">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">Django 博客开发入门教程：前言</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                            <span class="post-author"><a href="#">追梦人物</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>Django 是使用 Python 编写的一个开源 Web 框架，可以用来快速搭建一个高性能的网站。</p>
                        <blockquote><p>Django makes it easier to build better Web apps more quickly and with less
                            code.</p>
                            <p>Django 让你以更快的速度、更少的代码、更轻松的方式搭建更好的 Web 应用。</p>
                        </blockquote>
                        <p>本教程将带你使用 Django 快速开发属于自己的 Blog 网站。</p>
                        <h2>教程特点</h2>
                        <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。</p>
                        <p>带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django 开发的技巧。</p>
                        <h2>谁适合这个教程</h2>
                        <p><strong>本教程主要面向零基础的 Django 新人。</strong></p>
                        <p>只需要一点点 Python 语言的基础，就可以顺利阅读本教程。</p>
                        <p>如果你已有一定的 Django 开发经验，也能从本教程中学到更多的 Django 开发技巧。</p>
                        <h2>在线预览</h2>
                        <p>点击预览：<a href=''>Django Blog Demo</a></p>
                        <p><img src='' alt=''/></p>
                        <h2>资源列表</h2>
                        <p>项目完整代码托管在 GitHub：<a href=''>Django Blog Tutorial</a></p>
                        <p>博客前端模板托管在 GitHub：<a href=''>博客模板</a></p>
                        <h2>获取帮助</h2>
                        <p>在项目开发中遇到问题，即时获取帮助。</p>
                        <p>Django 学习小组 QQ 群，扫描下方二维码加入。</p>
                        <p><img src='' alt=''/></p>
                        <p>或者你也可以将问题的详细描述通过邮件发送至 <a href='mailto:djangostudyteam@163.com' target='_blank'>djangostudyteam@163.com</a>，一般会在
                            24 小时内答复。</p>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="#" method="post" class="comment-form">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            <li class="comment-item">
                                <span class="nickname">追梦人物</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>
                                <div class="text">
                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">zmrenwu</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>
                                <div class="text">
                                    本能有可能会冲破格局，但格局有时候也会拘住本能。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">蝙蝠侠</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>
                                <div class="text">
                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">长江七号</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>
                                <div class="text">
                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
            </main>
            <aside class="col-md-4">
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>